### ISSUE TITLE
Error when ngModel initialized with a non string value

### ISSUE THREAD

**Issue by tanvir-bd** [oferh/ng2-completer#307]
I have reactive form like bellow:

component.ts:
```
public colors = ["aliceblue","antiquewhite","aqua","aquamarine","azure","beige",
"bisque","black","blanchedalmond"];


      form = new FormGroup({
          ItemNames: new FormArray([
            new FormControl([null]),
          ])
        });


    onSubmit() {
      console.log(this.ItemNames.value);
      console.log(this.form.value);  
    }

```
component.html:

```
<form [formGroup]="form" (ngSubmit)="onSubmit()">
<div class="card">
    <div class="card-block">
        <div class="form-group row"  formArrayName="ItemNames">
            <div class="col-3 pr-0 border-right-0 with-chevron">
                <ng2-completer *ngFor="let ItemName of ItemNames.controls; let i=index"
                              #openCloseExample
                               class="completer-limit"                       
                               [datasource]="dataService4"
                               [inputClass]="'form-control'"
                               [openOnFocus]="true"
                               (opened)="onOpened($event)"
                               (focus)="openCloseFocused = true"
                               (blur)="openCloseFocused = false"
                               [minSearchLength]="0"
                               [placeholder]="'search color'"
                               [autoHighlight]="true"
                               [fillHighlighted]="false">
                </ng2-completer>
            </div>
```

How can I provide form control name here like formControlName="i" in ng2-completetr. I have tried in different ways but no luck until now. Could you please help me for this issue?

**Comment by oferh** [comment]
Does it work if you use `input` instead of `ng2-completer`? are you trying to create the controls dynamically?

**Comment by tanvir-bd** [comment]
Thanks oferh. I am so glad to see you :). Yes without ng2-completer it works 100%.

**Comment by oferh** [comment]
@tanvir-bd hope I can help.
can you create a plunker that reproduces it? you can use [this one](https://plnkr.co/edit/xU98ux?p=info) as base

**Comment by tanvir-bd** [comment]
Hello oferh. Here is the plunker : https://plnkr.co/edit/uYyAadCah7Y9qN4gt6yz?p=preview

**Comment by oferh** [comment]
it's very similar to #220 getting:

```
ERROR TypeError: t.term.toLocaleLowerCase is not a function
    at eval (https://unpkg.com/ng2-completer:1:29706)
    at Array.findIndex (native)
    at t.getBestMatchIndex (https://unpkg.com/ng2-completer:1:29646)
    at SafeSubscriber.eval [as _next] (https://unpkg.com/ng2-completer:1:30624)
    at SafeSubscriber.__tryOrUnsub (https://unpkg.com/rxjs/Subscriber.js:238:16)
    at SafeSubscriber.next (https://unpkg.com/rxjs/Subscriber.js:185:22)
    at Subscriber._next (https://unpkg.com/rxjs/Subscriber.js:125:26)
    at Subscriber.next (https://unpkg.com/rxjs/Subscriber.js:89:18)
    at CatchSubscriber.Subscriber._next (https://unpkg.com/rxjs/Subscriber.js:125:26)
    at CatchSubscriber.Subscriber.next (https://unpkg.com/rxjs/Subscriber.js:89:18)
    at i.Subject.next (https://unpkg.com/rxjs/Subject.js:55:25)
    at i.search (https://unpkg.com/ng2-completer:1:6020)
    at t.searchTimerComplete (https://unpkg.com/ng2-completer:1:29100)
    at SafeSubscriber.eval [as _next] (https://unpkg.com/ng2-completer:1:28343)
    at SafeSubscriber.__tryOrUnsub (https://unpkg.com/rxjs/Subscriber.js:238:16)
```

**Comment by tanvir-bd** [comment]
Thanks again. What do you suggest ?

**Comment by oferh** [comment]
Will need to fix this issue and release a new version, will try to do it today.

**Comment by tanvir-bd** [comment]
No problem. I will wait until then  :). Thanks for all of your efforts.

**Comment by tanvir-bd** [comment]
Is this issue solved ?

**Comment by oferh** [comment]
Yes check this [plunker](https://plnkr.co/edit/fUs1xorNkIU1QF7KTfIb?p=info) 

Note that the control init has changed from `[null]` to `null` :

```
cities: new FormArray([
      new FormControl(null),
    ]),
```

**Comment by tanvir-bd** [comment]
Wow you are genius. Let me tell you one thing. I will use this drop down for 20,000 value very soon. I think ng2-completer will be very handy. I have similar post here: https://stackoverflow.com/questions/45977026/ng2-completer-with-nested-dropdown 

If you want, you can answer there. I will accept answer and will put up vote.

Thanks once again :)

**Comment by oferh** [comment]
@tanvir-bd happy to help!
