### ISSUE TITLE
Unexpected value 'Ng2CompleterModule' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by jjacobs33589** [oferh/ng2-completer#44]
I'm trying to use your ng2-completer component inside of an ionic 2 project and I'm getting the following error.

`ngc error: Error: Unexpected value 'Ng2CompleterModule' imported by the module 'AppModule'
    at C:\Users\Hyrum\Documents\ProjectDev\test\ionic-conference-app\node_modules\@angular\compiler\bundles\compiler.umd.js:14109:37
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (C:\Users\Hyrum\Documents\ProjectDev\test\ionic-conference-app\node_modules\@angular\compiler\bundles\compiler.umd.js:14094:46)
    at C:\Users\Hyrum\Documents\ProjectDev\test\ionic-conference-app\node_modules\@angular\compiler\bundles\compiler.umd.js:12936:58
    at Array.forEach (native)
    at OfflineCompiler.analyzeModules (C:\Users\Hyrum\Documents\ProjectDev\test\ionic-conference-app\node_modules\@angular\compiler\bundles\compiler.umd.js:12935:21)
    at CodeGenerator.codegen (C:\Users\Hyrum\Documents\ProjectDev\test\ionic-conference-app\node_modules\@angular\compiler-cli\src\codegen.js:105:47)
    at codegen (C:\Users\Hyrum\Documents\ProjectDev\test\ionic-conference-app\node_modules\@angular\compiler-cli\src\main.js:7:81)
    at Object.main (C:\Users\Hyrum\Documents\ProjectDev\test\ionic-conference-app\node_modules\@angular\tsc-wrapped\src\main.js:30:16)
    at Object.<anonymous> (C:\Users\Hyrum\Documents\ProjectDev\test\ionic-conference-app\node_modules\@angular\compiler-cli\src\main.js:14:9)

[14:26:22]  ngc error: Compilation failed

[14:26:22]
[14:26:22]  bundle prod started ...
[14:26:22]  Error: Could not resolve entry (.tmp/app/main.prod.js)
    at C:\Users\Hyrum\Documents\ProjectDev\test\ionic-conference-app\node_modules\rollup\dist\rollup.js:8602:28
    at process._tickCallback (node.js:369:9)
[14:26:22]  sass started ...
[14:26:24]  sass finished in 1.65 s
[14:26:24]  minify started ...
[14:26:24]  cleancss started ...
[14:26:24]  uglifyjs started ...
[14:26:24]  Error: ENOENT: no such file or directory, open 'C:\Users\Hyrum\Documents\ProjectDev\test\ionic-conference-app\www\build\main.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at addFile (C:\Users\Hyrum\Documents\ProjectDev\test\ionic-conference-app\node_modules\uglify-js\tools\node.js:68:22)
    at C:\Users\Hyrum\Documents\ProjectDev\test\ionic-conference-app\node_modules\uglify-js\tools\node.js:79:17
    at Array.forEach (native)
    at Object.exports.minify (C:\Users\Hyrum\Documents\ProjectDev\test\ionic-conference-app\node_modules\uglify-js\tools\node.js:77:26)
    at runUglifyInternal (C:\Users\Hyrum\Documents\ProjectDev\test\ionic-conference-app\node_modules\@ionic\app-scripts\dist\uglifyjs.js:34:19)
    at runUglify (C:\Users\Hyrum\Documents\ProjectDev\test\ionic-conference-app\node_modules\@ionic\app-scripts\dist\uglifyjs.js:23:28)
    at Object.uglifyjs (C:\Users\Hyrum\Documents\ProjectDev\test\ionic-conference-app\node_modules\@ionic\app-scripts\dist\uglifyjs.js:9:12)
[14:26:25]  cleancss finished in 1.07 s
[14:26:25]  minify finished in 1.07 s
[14:26:25]  build prod finished in 6.66 s
`

I've been unsuccessful in getting it to work in my application so I cloned this [sample ionic project](https://github.com/driftyco/ionic-conference-app) and built it according to the instructions given on the front page.
run "npm install" from the project root.
Install the ionic CLI with "npm install -g ionic"
run the project in a browser with "ionic serve"

The project runs fine and everything in it works. 

I then add the ng2-completer module using the instructions given [here ](https://github.com/oferh/ng2-completer)and when I try to run the project again I get the above error.

I've looked for quite a bit for a solution and found [this similar issue](https://github.com/gevgeny/angular2-highcharts/issues/75).

Any help would be greatly appreciated

**Comment by oferh** [comment]
@jjacobs33589 I'm not familiar with Ionic but I can see that it uses `ngc` so it might be better to import the source code and not the bundled package. try to:
```
import { Ng2CompleterModule } from "ng2-completer/src/ng2-completer.module";
```

**Comment by jjacobs33589** [comment]
I did try that and it yielded a dozen more issues. In looking into it more I came across [this](https://github.com/zyramedia/ng2-chartjs2/issues/7) and wondered if it might be possible to include the metadata.json files with the ng2-completer component.

**Comment by armno** [comment]
@oferh importing the source module brings another error from `ngc`

```
Error: Error encountered resolving symbol values statically. Calling function 'require', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol CompleterListCmp in ...
```

Probably `ngc` doesn't work with `require()` in `CompleterListCmp` ? https://angular.io/docs/ts/latest/cookbook/aot-compiler.html#!#tree-shaking (notes in Rollup section)

**Comment by armno** [comment]
Followup from my last comment, I commented out all `require()` in all components and use HTML and CSS paths in `@Component` decorator, `ngc` produces another error

```
Error: Error encountered resolving symbol values statically. Expression form not supported (position 10:54 in the original .ts file), resolving symbol CompleterService
```

which are these 2 lines

```ts
@Inject(LocalData) private localDataFactory: () => LocalData,
@Inject(RemoteData) private remoteDataFactory: () => RemoteData
```

I changed to this

```diff
-@Inject(LocalData) private localDataFactory: () => LocalData,
+@Inject(LocalData) private localDataFactory: LocalData,
-@Inject(RemoteData) private remoteDataFactory: () => RemoteData
+@Inject(RemoteData) private remoteDataFactory: RemoteData
```

Which then the errors from `ngc` was gone but I'm not sure what I was doing. Totally not familiar with using `@Inject()` decorator 😅

**Comment by oferh** [comment]
@armno it's not `Inject` that caused the issue it's about `ngc` and  the need for the code to statically analyzed

**Comment by armno** [comment]
@oferh any guide on how to transform those 2 lines into something that can be statically analyzed by `ngc`? for example, use exported functions like what ng2-translate did here https://github.com/ocombe/ng2-translate#usage

**Comment by oferh** [comment]
related to #60

**Comment by kodeine** [comment]
@oferh there were some errors because at some places templates are using variables which were set as private in ts. so aot cant export that properly. I'll write those variables when i get home.

**Comment by kodeine** [comment]
@oferh 

```
[12:15:53]  Error: Error at 
            /Projects/SL/.tmp/node_modules/ng2-completer/src/components/ng2-completer/completer-list-item-cmp.ngfactory.ts:124:40
[12:15:53]  Property 'parts' is private and only accessible within class 'CompleterListItemCmp'. 
[12:15:53]  Error at 
            /Projects/SL/.tmp/components/auto-completer/completer-cmp-md.ngfactory.ts:216:18
[12:15:53]  Property 'completer' is private and only accessible within class 'CompleterCmpMd'. 
[12:15:53]  ngc failed 
[12:15:53]  ionic-app-script task: "build" 
[12:15:53]  Error: Error 
```

**Comment by farantesrodrigues** [comment]
Hi guys, I guess you already know about this issue but just to let you know that I tried installing via jspm and it also fails :

Error: (SystemJS) Unexpected value 'Ng2CompleterModule' imported by the module 'PublicModule'
	Error: Unexpected value 'Ng2CompleterModule' imported by the module 'PublicModule'
	    at eval (https://192.168.33.33:3000/jspm_packages/npm/@angular/compiler@2.0.2/bundles/compiler.umd.js:13523:25)
	    at Array.forEach (native)
	    at CompileMetadataResolver.getNgModuleMetadata (https://192.168.33.33:3000/jspm_packages/npm/@angular/compiler@2.0.2/bundles/compiler.umd.js:13509:40)
	    at RuntimeCompiler._compileComponents (https://192.168.33.33:3000/jspm_packages/npm/@angular/compiler@2.0.2/bundles/compiler.umd.js:15936:47)
	    at RuntimeCompiler._compileModuleAndComponents (https://192.168.33.33:3000/jspm_packages/npm/@angular/compiler@2.0.2/bundles/compiler.umd.js:15878:37)
	    at RuntimeCompiler.compileModuleAsync (https://192.168.33.33:3000/jspm_packages/npm/@angular/compiler@2.0.2/bundles/compiler.umd.js:15869:21)
	    at PlatformRef_._bootstrapModuleWithZone (https://192.168.33.33:3000/jspm_packages/npm/@angular/core@2.0.2/bundles/core.umd.js:4898:25)
	    at PlatformRef_.bootstrapModule (https://192.168.33.33:3000/jspm_packages/npm/@angular/core@2.0.2/bundles/core.umd.js:4881:21)
	    at execute (https://192.168.33.33:3000/app/main.ts!transpiled:31:65)
	Error loading https://192.168.33.33:3000/app/main.ts
	    at eval (https://192.168.33.33:3000/jspm_packages/npm/@angular/compiler@2.0.2/bundles/compiler.umd.js:13523:25)
	    at Array.forEach (native)
	    at CompileMetadataResolver.getNgModuleMetadata (https://192.168.33.33:3000/jspm_packages/npm/@angular/compiler@2.0.2/bundles/compiler.umd.js:13509:40)
	    at RuntimeCompiler._compileComponents (https://192.168.33.33:3000/jspm_packages/npm/@angular/compiler@2.0.2/bundles/compiler.umd.js:15936:47)
	    at RuntimeCompiler._compileModuleAndComponents (https://192.168.33.33:3000/jspm_packages/npm/@angular/compiler@2.0.2/bundles/compiler.umd.js:15878:37)
	    at RuntimeCompiler.compileModuleAsync (https://192.168.33.33:3000/jspm_packages/npm/@angular/compiler@2.0.2/bundles/compiler.umd.js:15869:21)
	    at PlatformRef_._bootstrapModuleWithZone (https://192.168.33.33:3000/jspm_packages/npm/@angular/core@2.0.2/bundles/core.umd.js:4898:25)
	    at PlatformRef_.bootstrapModule (https://192.168.33.33:3000/jspm_packages/npm/@angular/core@2.0.2/bundles/core.umd.js:4881:21)
	    at execute (https://192.168.33.33:3000/app/main.ts!transpiled:31:65)
	Error loading https://192.168.33.33:3000/app/main.ts

**Comment by oferh** [comment]
`ngc` is supported in `0.3.1`

**Comment by jjacobs33589** [comment]
Thank you! I added this into my project yesterday and it appears to be working just as it should. No build issues
