### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'core') at  node_modules\ng2-completer\bundles\ng2-completer.umd.js:4:96

### ISSUE THREAD

**Issue by rahulm6** [oferh/ng2-completer#463]
I am getting an error saying "Uncaught TypeError: Cannot read properties of undefined (reading 'core') at  node_modules\ng2-completer\bundles\ng2-completer.umd.js:4:96 at node_modules\ng2-completer\bundles\ng2-completer.umd.js:5:2".

Can anyone help me in this.

**Comment by Guillaumecabasson** [comment]
Me too, does anyone have a solution ?
