### ISSUE TITLE
Template parse Error in angular cli project

### ISSUE THREAD

**Issue by pakbaz** [oferh/ng2-completer#70]
I am trying to use this in my angular 2 Cli project. I think I have everything setup correctly.
Here is what my app module look like:

```
import {BrowserModule} from '@angular/platform-browser';
import {CommonModule} from '@angular/common';
import {NgModule} from '@angular/core';
import {HttpModule} from '@angular/http';
import {FormsModule} from '@angular/forms';
import {RouterModule} from "@angular/router";

import 'rxjs/Rx';


//Material Design Lite
import {MdlModule} from "angular2-mdl";

//Angular2 Grid
import {NgGridModule} from "angular2-grid";


import {AppComponent} from "./app.component";
import {routing} from "./app.routing";

import { WidgetsModule } from './widgets/widgets.module';
import { PageHeaderModule } from './page-header/page-header.module';
import { Ng2CompleterModule } from "ng2-completer";

import {
  AppConstants, UserService}
  from "./shared";

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    CommonModule,
    Ng2CompleterModule,
    FormsModule,
    HttpModule,
    RouterModule.forRoot([], {useHash: false}),
    routing,
    MdlModule,
    NgGridModule,
    WidgetsModule,
    PageHeaderModule
  ],
  providers: [
    AppConstants,
    UserService
  ],
  bootstrap: [AppComponent]
})
export class AppModule {
}
```

and here is what my component looks like (used the example):

```
import { Component} from '@angular/core';
import { CompleterService, CompleterData } from 'ng2-completer';


@Component({
  selector: 'oxy-search-box',
  // templateUrl: './search-box.component.html',
  template: '<ng2-completer [(ngModel)]="searchStr" [dataService]="dataService" [minSearchLength]="0"></ng2-completer>',
  styleUrls: ['./search-box.component.scss']
})
export class SearchBoxComponent{
  private searchStr: string;
  private dataService: CompleterData;
  private searchData = [
    { color: 'red', value: '#f00' },
    { color: 'green', value: '#0f0' },
    { color: 'blue', value: '#00f' },
    { color: 'cyan', value: '#0ff' },
    { color: 'magenta', value: '#f0f' },
    { color: 'yellow', value: '#ff0' },
    { color: 'black', value: '#000' }
  ];

  constructor(private completerService: CompleterService) { 
    this.dataService = completerService.local(this.searchData, 'color', 'color'); 
  }

}
```

I get this error when I run the project

```
zone.js:388Unhandled Promise rejection: Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'ng2-completer'.
1. If 'ng2-completer' is an Angular component and it has 'ngModel' input, then verify that it is part of this module.
2. If 'ng2-completer' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("<ng2-completer [ERROR ->][(ngModel)]="searchStr" [dataService]="dataService" [minSearchLength]="0"></ng2-completer>"): SearchBoxComponent@0:15
Can't bind to 'dataService' since it isn't a known property of 'ng2-completer'.
1. If 'ng2-completer' is an Angular component and it has 'dataService' input, then verify that it is part of this module.
2. If 'ng2-completer' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("<ng2-completer [(ngModel)]="searchStr" [ERROR ->][dataService]="dataService" [minSearchLength]="0"></ng2-completer>"): SearchBoxComponent@0:39
Can't bind to 'minSearchLength' since it isn't a known property of 'ng2-completer'.
1. If 'ng2-completer' is an Angular component and it has 'minSearchLength' input, then verify that it is part of this module.
2. If 'ng2-completer' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("<ng2-completer [(ngModel)]="searchStr" [dataService]="dataService" [ERROR ->][minSearchLength]="0"></ng2-completer>"): SearchBoxComponent@0:67
'ng2-completer' is not a known element:
1. If 'ng2-completer' is an Angular component, then verify that it is part of this module.
2. If 'ng2-completer' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<ng2-completer [(ngModel)]="searchStr" [dataService]="dataService" [minSearchLength]="0"></ng2-comple"): SearchBoxComponent@0:0 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:(…) Error: Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'ng2-completer'.
1. If 'ng2-completer' is an Angular component and it has 'ngModel' input, then verify that it is part of this module.
2. If 'ng2-completer' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("<ng2-completer [ERROR ->][(ngModel)]="searchStr" [dataService]="dataService" [minSearchLength]="0"></ng2-completer>"): SearchBoxComponent@0:15
Can't bind to 'dataService' since it isn't a known property of 'ng2-completer'.
1. If 'ng2-completer' is an Angular component and it has 'dataService' input, then verify that it is part of this module.
2. If 'ng2-completer' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("<ng2-completer [(ngModel)]="searchStr" [ERROR ->][dataService]="dataService" [minSearchLength]="0"></ng2-completer>"): SearchBoxComponent@0:39
Can't bind to 'minSearchLength' since it isn't a known property of 'ng2-completer'.
1. If 'ng2-completer' is an Angular component and it has 'minSearchLength' input, then verify that it is part of this module.
2. If 'ng2-completer' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("<ng2-completer [(ngModel)]="searchStr" [dataService]="dataService" [ERROR ->][minSearchLength]="0"></ng2-completer>"): SearchBoxComponent@0:67
'ng2-completer' is not a known element:
1. If 'ng2-completer' is an Angular component, then verify that it is part of this module.
2. If 'ng2-completer' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<ng2-completer [(ngModel)]="searchStr" [dataService]="dataService" [minSearchLength]="0"></ng2-comple"): SearchBoxComponent@0:0
    at TemplateParser.parse (http://localhost:4200/main.bundle.js:18562:19)
    at RuntimeCompiler._compileTemplate (http://localhost:4200/main.bundle.js:41134:51)
    at http://localhost:4200/main.bundle.js:41039:83
    at Set.forEach (native)
    at compile (http://localhost:4200/main.bundle.js:41039:47)
    at ZoneDelegate.invoke (http://localhost:4200/main.bundle.js:107184:26)
    at Zone.run (http://localhost:4200/main.bundle.js:107066:43)
    at http://localhost:4200/main.bundle.js:107454:57
    at ZoneDelegate.invokeTask (http://localhost:4200/main.bundle.js:107217:35)
    at Zone.runTask (http://localhost:4200/main.bundle.js:107106:47)
```

**Comment by oferh** [comment]
It's hard to tell without the full source code, can you try using ng2-completer not as a nested component and see if you still get the error?

**Comment by gelliott181** [comment]
I too use the CLI at version beta.16 currently. I'm able to import and use the component with all your properties, however I import inside of a submodule because I lazy load. Do you only have an app.module?

**Comment by pakbaz** [comment]
Sorry for late response. I got it working. it was because I had it defined in both app module and my nested module again.
