### ISSUE TITLE
How to use the ng2-completer with other way of bootstraping the application

### ISSUE THREAD

**Issue by simoazzo** [oferh/ng2-completer#92]
Hi Guys,

Can you please guide me how to use the ng2-completer with the other way round if I have bootstrapping?

I do not have AppModule. I have the following, from the angular2-seed project:

```
bootstrap(AppComponent, [
  disableDeprecatedForms(),
  provideForms(),
  {
    //this for ng2-tag-inputs https://github.com/Gbuomprisco/ng2-tag-input
          provide: PLATFORM_DIRECTIVES,
          useValue: [REACTIVE_FORM_DIRECTIVES],
          multi: true
  },
  APP_ROUTER_PROVIDERS,
  {
    provide: APP_BASE_HREF,
    useValue: '<%= APP_BASE %>'
  },

]);
```
But I cannot make it working.

This is the exception thrown when trying to pass the injection for Completer Service in Constructor:

```
EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in :0:0
ORIGINAL EXCEPTION: No provider for t!
ORIGINAL STACKTRACE:
Error: DI Exception
    at NoProviderError.BaseException [as constructor] (http://localhost:12646/angular2-seed-master/node_modules/@angular/core/bundles/core.umd.js:4383:27)
    at NoProviderError.AbstractProviderError [as constructor] (http://localhost:12646/angular2-seed-master/node_modules/@angular/core/bundles/core.umd.js:4504:20)
    at new NoProviderError (http://localhost:12646/angular2-seed-master/node_modules/@angular/core/bundles/core.umd.js:4540:20)
    at ReflectiveInjector_._throwOrNull (http://localhost:12646/angular2-seed-master/node_modules/@angular/core/bundles/core.umd.js:6427:23)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:12646/angular2-seed-master/node_modules/@angular/core/bundles/core.umd.js:6455:29)
    at ReflectiveInjector_._getByKey (http://localhost:12646/angular2-seed-master/node_modules/@angular/core/bundles/core.umd.js:6418:29)
    at ReflectiveInjector_.get (http://localhost:12646/angular2-seed-master/node_modules/@angular/core/bundles/core.umd.js:6227:25)
    at ElementInjector.get (http://localhost:12646/angular2-seed-master/node_modules/@angular/core/bundles/core.umd.js:11573:52)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:12646/angular2-seed-master/node_modules/@angular/core/bundles/core.umd.js:6452:28)
    at ReflectiveInjector_._getByKey (http://localhost:12646/angular2-seed-master/node_modules/@angular/core/bundles/core.umd.js:6418:29)
ERROR CONTEXT:
[object Object]
```

Any help would be much appreciated.

Kind Regards

**Comment by simoazzo** [comment]
How can I add the module if using the bootstraping way?

Thank you

**Comment by oferh** [comment]
according to angular [changelog](https://github.com/angular/angular/blob/master/CHANGELOG.md) the way you are using is not supported since of rc.5:

```
Platform directives / pipes need to be provided via configureModule and can no longer be provided via the PLATFORM_PIPES / PLATFORM_DIRECTIVES tokens.
```
